from typing import TypeAlias, Tuple, Dict

PdfFieldRef: TypeAlias = str | Tuple[str, ...]

FIELD_MAP: Dict[str, Dict[str, PdfFieldRef]] = {
    "character_sheet": {
        # Identifiers
        "character_name": "CharacterName",

        # Class / level (stored as JSONB in the DB; parsed downstream)
        "class_levels": "ClassLevel",

        # Background / identity
        "background": "Background",
        "player_name": "PlayerName",
        "race": "Race ",
        "alignment": "Alignment",
        "experience_points": "XP",

        # Core stats
        "strength_score": "STR",
        "dexterity_score": "DEX",
        "constitution_score": "CON",
        "intelligence_score": "INT",
        "wisdom_score": "WIS",
        "charisma_score": "CHA",

        # Combat basics
        "armor_class": "AC",
        "initiative": "Initiative",
        "speed": "Speed",
        "proficiency_bonus": "ProfBonus",
        "inspiration": "Inspiration",

        # Hit points
        "hit_point_maximum": "HPMax",
        "current_hit_points": "HPCurrent",
        "temporary_hit_points": "HPTemp",

        # Hit dice (stored as TEXT[] in the DB; constructed downstream)
        "hit_dice_total": ("HDTotal", "HD"),

        # Currency
        "copper_pieces": "CP",
        "silver_pieces": "SP",
        "electrum_pieces": "EP",
        "gold_pieces": "GP",
        "platinum_pieces": "PP",

        # Passive perception
        "passive_wisdom_perception": "Passive",

        # Narrative blocks
        "other_proficiencies_and_languages": "ProficienciesLang",
        "attacks_and_spellcasting": "AttacksSpellcasting",
        "features_and_traits": "Features and Traits",
        "personality_traits": "PersonalityTraits ",
        "ideals": "Ideals",
        "bonds": "Bonds",
        "flaws": "Flaws",

        # Equipment (raw list; resolved to item ids downstream)
        "equipment_item_ids": "Equipment",

        # Appearance / bio
        "age": "Age",
        "height": "Height",
        "weight": "Weight",
        "eyes": "Eyes",
        "skin": "Skin",
        "hair": "Hair",
        "character_appearance": "CHARACTER IMAGE",
        "character_backstory": "Backstory",
        "treasure": "Treasure",
        "allies_and_organizations": "Allies",
        "additional_features_and_traits": "Feat+Traits",

        # Foreign-key pointers (filled by application logic)
        "skills_id": (),
        "spells_id": (),
    },

    "player_skills": {
        "acrobatics_modifier": "Acrobatics",
        "acrobatics_proficient": "Acrobatics",
        "animal_handling_modifier": "Animal",
        "animal_handling_proficient": "Animal",
        "arcana_modifier": "Arcana",
        "arcana_proficient": "Arcana",
        "athletics_modifier": "Athletics",
        "athletics_proficient": "Athletics",
        "deception_modifier": "Deception ",
        "deception_proficient": "Deception ",
        "history_modifier": "History ",
        "history_proficient": "History ",
        "insight_modifier": "Insight",
        "insight_proficient": "Insight",
        "intimidation_modifier": "Intimidation",
        "intimidation_proficient": "Intimidation",
        "investigation_modifier": "Investigation ",
        "investigation_proficient": "Investigation ",
        "medicine_modifier": "Medicine",
        "medicine_proficient": "Medicine",
        "nature_modifier": "Nature",
        "nature_proficient": "Nature",
        "perception_modifier": "Perception ",
        "perception_proficient": "Perception ",
        "performance_modifier": "Performance",
        "performance_proficient": "Performance",
        "persuasion_modifier": "Persuasion",
        "persuasion_proficient": "Persuasion",
        "religion_modifier": "Religion",
        "religion_proficient": "Religion",
        "sleight_of_hand_modifier": "SleightofHand",
        "sleight_of_hand_proficient": "SleightofHand",
        "stealth_modifier": "Stealth ",
        "stealth_proficient": "Stealth ",
        "survival_modifier": "Survival",
        "survival_proficient": "Survival",
    },

    "player_spells": {
        "spellcasting_class": "Spellcasting Class 2",
        "spellcasting_ability": "SpellcastingAbility 2",
        "spell_save_dc": "SpellSaveDC  2",
        "spell_attack_bonus": "SpellAtkBonus 2",

        # Raw spell fields (parse downstream)
        "spells": (
            "Spells 1014",
            "Spells 1015",
            "Spells 1016",
            "Spells 1017",
            "Spells 1018",
            "Spells 1019",
            "Spells 1020",
            "Spells 1021",
            "Spells 1022",
            "Spells 1023",
            "Spells 1024",
            "Spells 1025",
            "Spells 1026",
            "Spells 1027",
            "Spells 1028",
            "Spells 1029",
            "Spells 1030",
            "Spells 1031",
            "Spells 1032",
            "Spells 1033",
            "Spells 1034",
            "Spells 1035",
            "Spells 1036",
            "Spells 1037",
            "Spells 1038",
            "Spells 1039",
            "Spells 1040",
            "Spells 1041",
            "Spells 1042",
            "Spells 1043",
            "Spells 1044",
            "Spells 1045",
            "Spells 1046",
            "Spells 1047",
            "Spells 1048",
            "Spells 1049",
            "Spells 1050",
            "Spells 1051",
            "Spells 1052",
            "Spells 1053",
            "Spells 1054",
            "Spells 1055",
            "Spells 1056",
            "Spells 1057",
            "Spells 1058",
            "Spells 1059",
            "Spells 1060",
            "Spells 1061",
            "Spells 1062",
            "Spells 1063",
            "Spells 1064",
            "Spells 1065",
            "Spells 1066",
            "Spells 1067",
            "Spells 1068",
            "Spells 1069",
            "Spells 1070",
            "Spells 1071",
            "Spells 1072",
            "Spells 1073",
            "Spells 1074",
            "Spells 1075",
            "Spells 1076",
            "Spells 1077",
            "Spells 1078",
            "Spells 1079",
            "Spells 1080",
            "Spells 1081",
            "Spells 1082",
            "Spells 1083",
            "Spells 1084",
            "Spells 1085",
            "Spells 1086",
            "Spells 1087",
            "Spells 1088",
            "Spells 1089",
            "Spells 1090",
            "Spells 1091",
            "Spells 1092",
            "Spells 1093",
            "Spells 1094",
            "Spells 1095",
            "Spells 1096",
            "Spells 1097",
            "Spells 1098",
            "Spells 1099",
        ),

        # Slots totals (PDF uses 19..27 for levels 1..9)
        "slots_1_total": "SlotsTotal 19",
        "slots_2_total": "SlotsTotal 20",
        "slots_3_total": "SlotsTotal 21",
        "slots_4_total": "SlotsTotal 22",
        "slots_5_total": "SlotsTotal 23",
        "slots_6_total": "SlotsTotal 24",
        "slots_7_total": "SlotsTotal 25",
        "slots_8_total": "SlotsTotal 26",
        "slots_9_total": "SlotsTotal 27"
    },
}
