# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
import baml_py

from . import stream_types, types, type_builder
from .parser import LlmResponseParser, LlmStreamParser
from .runtime import DoNotUseDirectlyCallManager, BamlCallOptions
from .globals import DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME as __runtime__


class BamlAsyncClient:
    __options: DoNotUseDirectlyCallManager
    __stream_client: "BamlStreamClient"
    __http_request: "BamlHttpRequestClient"
    __http_stream_request: "BamlHttpStreamRequestClient"
    __llm_response_parser: LlmResponseParser
    __llm_stream_parser: LlmStreamParser

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options
        self.__stream_client = BamlStreamClient(options)
        self.__http_request = BamlHttpRequestClient(options)
        self.__http_stream_request = BamlHttpStreamRequestClient(options)
        self.__llm_response_parser = LlmResponseParser(options)
        self.__llm_stream_parser = LlmStreamParser(options)

    def with_options(self,
        tb: typing.Optional[type_builder.TypeBuilder] = None,
        client_registry: typing.Optional[baml_py.baml_py.ClientRegistry] = None,
        client: typing.Optional[str] = None,
        collector: typing.Optional[typing.Union[baml_py.baml_py.Collector, typing.List[baml_py.baml_py.Collector]]] = None,
        env: typing.Optional[typing.Dict[str, typing.Optional[str]]] = None,
        tags: typing.Optional[typing.Dict[str, str]] = None,
        on_tick: typing.Optional[typing.Callable[[str, baml_py.baml_py.FunctionLog], None]] = None,
    ) -> "BamlAsyncClient":
        options: BamlCallOptions = {}
        if tb is not None:
            options["tb"] = tb
        if client_registry is not None:
            options["client_registry"] = client_registry
        if client is not None:
            options["client"] = client
        if collector is not None:
            options["collector"] = collector
        if env is not None:
            options["env"] = env
        if tags is not None:
            options["tags"] = tags
        if on_tick is not None:
            options["on_tick"] = on_tick
        return BamlAsyncClient(self.__options.merge_options(options))

    @property
    def stream(self):
      return self.__stream_client

    @property
    def request(self):
      return self.__http_request

    @property
    def stream_request(self):
      return self.__http_stream_request

    @property
    def parse(self):
      return self.__llm_response_parser

    @property
    def parse_stream(self):
      return self.__llm_stream_parser

    async def ParseSpellSource(self, source_ref: str,hint: typing.Optional[str] = None,
        baml_options: BamlCallOptions = {},
    ) -> types.SpellInsertRow:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            # Use streaming internally when on_tick is provided
            __stream__ = self.stream.ParseSpellSource(source_ref=source_ref,hint=hint,
                baml_options=baml_options)
            return await __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = await self.__options.merge_options(baml_options).call_function_async(function_name="ParseSpellSource", args={
                "source_ref": source_ref,"hint": hint,
            })
            return typing.cast(types.SpellInsertRow, __result__.cast_to(types, types, stream_types, False, __runtime__))
    async def PlanDiscordMessage(self, user_message: str,discord_context: str,attachment_summary: str,world_state_snapshot: str,planner_instructions: typing.Optional[str] = None,
        baml_options: BamlCallOptions = {},
    ) -> types.PlannerDecision:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            # Use streaming internally when on_tick is provided
            __stream__ = self.stream.PlanDiscordMessage(user_message=user_message,discord_context=discord_context,attachment_summary=attachment_summary,world_state_snapshot=world_state_snapshot,planner_instructions=planner_instructions,
                baml_options=baml_options)
            return await __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = await self.__options.merge_options(baml_options).call_function_async(function_name="PlanDiscordMessage", args={
                "user_message": user_message,"discord_context": discord_context,"attachment_summary": attachment_summary,"world_state_snapshot": world_state_snapshot,"planner_instructions": planner_instructions,
            })
            return typing.cast(types.PlannerDecision, __result__.cast_to(types, types, stream_types, False, __runtime__))
    async def PlanRlmRootTurn(self, request: types.RootRlmRequest,
        baml_options: BamlCallOptions = {},
    ) -> types.RootRlmResponse:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            # Use streaming internally when on_tick is provided
            __stream__ = self.stream.PlanRlmRootTurn(request=request,
                baml_options=baml_options)
            return await __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = await self.__options.merge_options(baml_options).call_function_async(function_name="PlanRlmRootTurn", args={
                "request": request,
            })
            return typing.cast(types.RootRlmResponse, __result__.cast_to(types, types, stream_types, False, __runtime__))
    async def Roll(self, request: str,context: typing.Optional[str] = None,
        baml_options: BamlCallOptions = {},
    ) -> types.RollPlan:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            # Use streaming internally when on_tick is provided
            __stream__ = self.stream.Roll(request=request,context=context,
                baml_options=baml_options)
            return await __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = await self.__options.merge_options(baml_options).call_function_async(function_name="Roll", args={
                "request": request,"context": context,
            })
            return typing.cast(types.RollPlan, __result__.cast_to(types, types, stream_types, False, __runtime__))
    async def SummarizeCharacterSheetIngestion(self, result: types.CharacterSheetIngestionResult,
        baml_options: BamlCallOptions = {},
    ) -> types.CharacterSheetIngestionSummary:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            # Use streaming internally when on_tick is provided
            __stream__ = self.stream.SummarizeCharacterSheetIngestion(result=result,
                baml_options=baml_options)
            return await __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = await self.__options.merge_options(baml_options).call_function_async(function_name="SummarizeCharacterSheetIngestion", args={
                "result": result,
            })
            return typing.cast(types.CharacterSheetIngestionSummary, __result__.cast_to(types, types, stream_types, False, __runtime__))
    


class BamlStreamClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def ParseSpellSource(self, source_ref: str,hint: typing.Optional[str] = None,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[stream_types.SpellInsertRow, types.SpellInsertRow]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_async_stream(function_name="ParseSpellSource", args={
            "source_ref": source_ref,"hint": hint,
        })
        return baml_py.BamlStream[stream_types.SpellInsertRow, types.SpellInsertRow](
          __result__,
          lambda x: typing.cast(stream_types.SpellInsertRow, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.SpellInsertRow, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def PlanDiscordMessage(self, user_message: str,discord_context: str,attachment_summary: str,world_state_snapshot: str,planner_instructions: typing.Optional[str] = None,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[stream_types.PlannerDecision, types.PlannerDecision]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_async_stream(function_name="PlanDiscordMessage", args={
            "user_message": user_message,"discord_context": discord_context,"attachment_summary": attachment_summary,"world_state_snapshot": world_state_snapshot,"planner_instructions": planner_instructions,
        })
        return baml_py.BamlStream[stream_types.PlannerDecision, types.PlannerDecision](
          __result__,
          lambda x: typing.cast(stream_types.PlannerDecision, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.PlannerDecision, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def PlanRlmRootTurn(self, request: types.RootRlmRequest,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[stream_types.RootRlmResponse, types.RootRlmResponse]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_async_stream(function_name="PlanRlmRootTurn", args={
            "request": request,
        })
        return baml_py.BamlStream[stream_types.RootRlmResponse, types.RootRlmResponse](
          __result__,
          lambda x: typing.cast(stream_types.RootRlmResponse, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.RootRlmResponse, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def Roll(self, request: str,context: typing.Optional[str] = None,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[stream_types.RollPlan, types.RollPlan]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_async_stream(function_name="Roll", args={
            "request": request,"context": context,
        })
        return baml_py.BamlStream[stream_types.RollPlan, types.RollPlan](
          __result__,
          lambda x: typing.cast(stream_types.RollPlan, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.RollPlan, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def SummarizeCharacterSheetIngestion(self, result: types.CharacterSheetIngestionResult,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[stream_types.CharacterSheetIngestionSummary, types.CharacterSheetIngestionSummary]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_async_stream(function_name="SummarizeCharacterSheetIngestion", args={
            "result": result,
        })
        return baml_py.BamlStream[stream_types.CharacterSheetIngestionSummary, types.CharacterSheetIngestionSummary](
          __result__,
          lambda x: typing.cast(stream_types.CharacterSheetIngestionSummary, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.CharacterSheetIngestionSummary, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    

class BamlHttpRequestClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    async def ParseSpellSource(self, source_ref: str,hint: typing.Optional[str] = None,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="ParseSpellSource", args={
            "source_ref": source_ref,"hint": hint,
        }, mode="request")
        return __result__
    async def PlanDiscordMessage(self, user_message: str,discord_context: str,attachment_summary: str,world_state_snapshot: str,planner_instructions: typing.Optional[str] = None,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="PlanDiscordMessage", args={
            "user_message": user_message,"discord_context": discord_context,"attachment_summary": attachment_summary,"world_state_snapshot": world_state_snapshot,"planner_instructions": planner_instructions,
        }, mode="request")
        return __result__
    async def PlanRlmRootTurn(self, request: types.RootRlmRequest,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="PlanRlmRootTurn", args={
            "request": request,
        }, mode="request")
        return __result__
    async def Roll(self, request: str,context: typing.Optional[str] = None,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="Roll", args={
            "request": request,"context": context,
        }, mode="request")
        return __result__
    async def SummarizeCharacterSheetIngestion(self, result: types.CharacterSheetIngestionResult,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="SummarizeCharacterSheetIngestion", args={
            "result": result,
        }, mode="request")
        return __result__
    

class BamlHttpStreamRequestClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    async def ParseSpellSource(self, source_ref: str,hint: typing.Optional[str] = None,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="ParseSpellSource", args={
            "source_ref": source_ref,"hint": hint,
        }, mode="stream")
        return __result__
    async def PlanDiscordMessage(self, user_message: str,discord_context: str,attachment_summary: str,world_state_snapshot: str,planner_instructions: typing.Optional[str] = None,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="PlanDiscordMessage", args={
            "user_message": user_message,"discord_context": discord_context,"attachment_summary": attachment_summary,"world_state_snapshot": world_state_snapshot,"planner_instructions": planner_instructions,
        }, mode="stream")
        return __result__
    async def PlanRlmRootTurn(self, request: types.RootRlmRequest,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="PlanRlmRootTurn", args={
            "request": request,
        }, mode="stream")
        return __result__
    async def Roll(self, request: str,context: typing.Optional[str] = None,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="Roll", args={
            "request": request,"context": context,
        }, mode="stream")
        return __result__
    async def SummarizeCharacterSheetIngestion(self, result: types.CharacterSheetIngestionResult,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="SummarizeCharacterSheetIngestion", args={
            "result": result,
        }, mode="stream")
        return __result__
    

b = BamlAsyncClient(DoNotUseDirectlyCallManager({}))