# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions


from . import stream_types, types
from .runtime import DoNotUseDirectlyCallManager, BamlCallOptions

class LlmResponseParser:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def ParseSpellSource(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.SpellInsertRow:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ParseSpellSource", llm_response=llm_response, mode="request")
        return typing.cast(types.SpellInsertRow, __result__)

    def PlanDiscordMessage(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.PlannerDecision:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="PlanDiscordMessage", llm_response=llm_response, mode="request")
        return typing.cast(types.PlannerDecision, __result__)

    def PlanRlmRootTurn(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.RootRlmResponse:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="PlanRlmRootTurn", llm_response=llm_response, mode="request")
        return typing.cast(types.RootRlmResponse, __result__)

    def Roll(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.RollPlan:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="Roll", llm_response=llm_response, mode="request")
        return typing.cast(types.RollPlan, __result__)

    def SummarizeCharacterSheetIngestion(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.CharacterSheetIngestionSummary:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="SummarizeCharacterSheetIngestion", llm_response=llm_response, mode="request")
        return typing.cast(types.CharacterSheetIngestionSummary, __result__)

    

class LlmStreamParser:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def ParseSpellSource(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.SpellInsertRow:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ParseSpellSource", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.SpellInsertRow, __result__)

    def PlanDiscordMessage(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.PlannerDecision:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="PlanDiscordMessage", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.PlannerDecision, __result__)

    def PlanRlmRootTurn(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.RootRlmResponse:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="PlanRlmRootTurn", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.RootRlmResponse, __result__)

    def Roll(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.RollPlan:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="Roll", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.RollPlan, __result__)

    def SummarizeCharacterSheetIngestion(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.CharacterSheetIngestionSummary:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="SummarizeCharacterSheetIngestion", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.CharacterSheetIngestionSummary, __result__)

    