# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from pydantic import BaseModel, ConfigDict, Field

import baml_py

from . import types

StreamStateValueT = typing.TypeVar('StreamStateValueT')
class StreamState(BaseModel, typing.Generic[StreamStateValueT]):
    value: StreamStateValueT
    state: typing_extensions.Literal["Pending", "Incomplete", "Complete"]
# #########################################################################
# Generated classes (8)
# #########################################################################

class CharacterSheetIngestionError(BaseModel):
    # CharacterSheetIngestionError
    # 
    # Purpose
    # -------
    # Encodes a single ingestion error or warning emitted by deterministic host
    # code.
    # 
    # Fields
    # ------
    # - type: categorized error type.
    # - message: human-readable detail produced by host code.
    # - metadata: optional list payload used for structured followups (for example,
    # missing item names).
    # 
    # Notes
    # -----
    # The LLM must not invent new errors; it may only summarize these.

    type: typing.Optional[types.CharacterSheetIngestionErrorType] = Field(default=None, description='Machine-readable category for this issue (critical vs warning).')
    message: typing.Optional[str] = Field(default=None, description='Human-readable detail produced by host code; used for summarization.')
    metadata: typing.Optional[typing.List[str]] = Field(default=None, description='Optional list payload (e.g., missing item/spell names) for structured reporting.')

class CharacterSheetIngestionResult(BaseModel):
    # CharacterSheetIngestionResult
    # 
    # Purpose
    # -------
    # Represents the deterministic host runtime outcome of attempting to ingest a
    # single character-sheet PDF.
    # 
    # Fields
    # ------
    # - ingested: true if and only if the sheet was ingested successfully enough
    # to persist core character data.
    # - errors: optional list of structured errors and warnings.
    # 
    # Invariants
    # ----------
    # - If any error has type UnsupportedPDFSchema, then ingested must be false.
    # - ItemNotFound and SpellNotFound do not imply ingested=false.
    # 
    # Notes
    # -----
    # This object is produced by deterministic host code, not by the LLM.

    ingested: typing.Optional[bool] = Field(default=None, description='True iff the host deterministically ingested core character data; false only for critical failures like unsupported schema.')
    errors: typing.Optional[typing.List["CharacterSheetIngestionError"]] = Field(default=None, description='Optional list of structured errors/warnings emitted by deterministic host ingestion.')

class CharacterSheetIngestionSummary(BaseModel):
    # CharacterSheetIngestionSummary
    # 
    # Purpose
    # -------
    # User-facing summary derived from a deterministic ingestion result.
    # 
    # Fields
    # ------
    # - user_message: short Discord-ready message summarizing success/warnings.
    # - ingested: mirrors the deterministic result.ingested.
    # - has_warnings: true iff there exists any non-critical warning.
    # - critical_error: true iff any error is UnsupportedPDFSchema.
    # - missing_items: optional aggregated list of missing item names.
    # - missing_spells: optional aggregated list of missing spell names.
    # 
    # Invariants
    # ----------
    # - critical_error is true iff any error has type UnsupportedPDFSchema.
    # - has_warnings is true iff any error has a non-critical type.
    # 
    # Notes
    # -----
    # This is the object the bot should use to format responses and UI.

    user_message: typing.Optional[str] = Field(default=None, description='Discord-ready summary message derived from the deterministic result.')
    ingested: typing.Optional[bool] = Field(default=None, description='Mirrors the deterministic result.ingested.')
    has_warnings: typing.Optional[bool] = Field(default=None, description='True iff any non-critical warnings exist (ItemNotFound/SpellNotFound).')
    critical_error: typing.Optional[bool] = Field(default=None, description='True iff any error is UnsupportedPDFSchema; implies ingested=false.')
    missing_items: typing.Optional[typing.List[str]] = Field(default=None, description='Aggregated list of equipment/item names missing from the database, if provided by metadata.')
    missing_spells: typing.Optional[typing.List[str]] = Field(default=None, description='Aggregated list of spell names missing from the database, if provided by metadata.')

class DiceTerm(BaseModel):
    # DiceTerm
    # Purpose
    # -------
    # Represents a single dice term NdS (e.g., 2d6).
    # 
    # Fields
    # ------
    # - count: number of dice (>= 1)
    # - sides: number of sides per die (>= 2)
    # 
    # Invariants
    # ----------
    # - count must be >= 1.
    # - sides must be >= 2.
    # 
    # Notes
    # -----
    # Multiple DiceTerm entries may be combined within a RollPlan.

    count: typing.Optional[int] = None
    sides: typing.Optional[int] = None

class PlannerDecision(BaseModel):
    route: typing.Optional[str] = Field(default=None, description='Planner routing decision: one of \'message_only\', \'clarification\', or \'tool_calls\'.')
    assistant_message: typing.Optional[str] = Field(default=None, description='Natural-language message to send back immediately when route=\'message_only\'.')
    needs_clarification: typing.Optional[bool] = Field(default=None, description='True when the planner cannot safely select tools or answer without asking a follow-up question.')
    clarification_question: typing.Optional[str] = Field(default=None, description='Follow-up question to ask the user when needs_clarification=true and route=\'clarification\'.')
    tool_calls: typing.List["ToolCall"] = Field(description='Ordered list of tool calls the executor should validate and run when route=\'tool_calls\'.')

class RollPlan(BaseModel):
    # RollPlan
    # 
    # Purpose
    # -------
    # Encodes a fully specified, deterministic dice execution plan that can be
    # executed by host runtime code.
    # 
    # Fields
    # ------
    # - dice: list of DiceTerm entries defining all dice rolled per instance.
    # - modifier: flat integer modifier applied once per instance.
    # - repeat: number of independent instances to execute (>= 1).
    # - mode: RollMode indicating d20 resolution behavior.
    # - label: optional short description for UI/logging.
    # 
    # Invariants
    # ----------
    # - repeat must be >= 1.
    # - modifier applies once per instance, never per die.
    # - mode affects only d20 terms.
    # 
    # Notes
    # -----
    # RollPlan must be directly executable without additional inference.

    dice: typing.List["DiceTerm"]
    modifier: typing.Optional[int] = None
    repeat: typing.Optional[int] = None
    mode: typing.Optional[types.RollMode] = None
    label: typing.Optional[str] = None

class SpellInsertRow(BaseModel):
    # Purpose
    # -------
    # Represents one insertable record matching the Postgres `spells` table columns.
    # The host should insert exactly one row per parsed spell.
    # 
    # Fields
    # ------
    # - spell_name: spell name as printed in the source (non-empty)
    # - level: integer in [0, 9] (use 0 for cantrips)
    # - cast_time: human-readable casting time (non-empty)
    # - range: human-readable range (non-empty)
    # - duration: human-readable duration (non-empty)
    # - damage: dice expression (e.g., "3d8", "1d4+1") or null if not specified
    # - damage_type: one of DamageType or null if not specified
    # - is_elemental: true only for elemental damage types (see invariants)
    # - save_ability: one of SaveAbility or null if no saving throw
    # - component_verbal/component_somatic/component_material: V/S/M flags
    # - material_components: raw material text if present; else null
    # - is_ritual: true if the spell is marked as ritual
    # - details: non-empty summary + rules text (best effort)
    # 
    # Invariants
    # ----------
    # - `level` must be within [0, 9].
    # - At least one of component_verbal/component_somatic/component_material is true.
    # - If component_material is false then material_components must be null.
    # - If is_elemental is true, damage_type must be one of:
    # ACID, COLD, FIRE, LIGHTNING, POISON, THUNDER.
    # - If damage_type is null, is_elemental must be false.
    # 
    # Notes
    # -----
    # - Nullable fields mirror nullable DB columns and must not be fabricated.

    spell_name: typing.Optional[str] = Field(default=None, description='Spell title as printed at the top of the block (e.g., \'Arms of Hadar\'). Copy exact capitalization/punctuation.')
    level: typing.Optional[int] = Field(default=None, description='Spell level parsed from the header line like \'1st-level conjuration\'. Use 0 if the header says \'cantrip\'.')
    cast_time: typing.Optional[str] = Field(default=None, description='Value on the \'Casting Time:\' line (e.g., \'1 action\', \'1 bonus action\', \'1 reaction, which you take when ...\'). Copy as written.')
    range: typing.Optional[str] = Field(default=None, description='Value on the \'Range:\' line (e.g., \'Self (10-foot radius)\', \'60 feet\', \'Touch\'). Copy as written.')
    duration: typing.Optional[str] = Field(default=None, description='Value on the \'Duration:\' line (e.g., \'Instantaneous\', \'Concentration, up to 1 minute\'). Copy as written.')
    damage: typing.Optional[str] = Field(default=None, description='Dice expression for primary damage if explicitly stated (e.g., \'2d6\', \'1d4+1\'). Extract from rules text like \'takes 2d6 necrotic damage\'. Null if no damage dice are specified.')
    damage_type: typing.Optional[types.DamageType] = Field(default=None, description='Damage type associated with `damage` when present (e.g., \'necrotic\' -> NECROTIC). Null if no damage type is specified or if `damage` is null.')
    is_elemental: typing.Optional[bool] = Field(default=None, description='True only when `damage_type` is one of ACID/COLD/FIRE/LIGHTNING/POISON/THUNDER. Otherwise false (including when `damage_type` is null).')
    save_ability: typing.Optional[types.SaveAbility] = Field(default=None, description='Set if the spell text says the target must make an ability saving throw (e.g., \'Strength saving throw\' -> STR). Null if there is no saving throw.')
    component_verbal: typing.Optional[bool] = Field(default=None, description='True if the \'Components:\' line includes \'V\'. Example: \'Components: V, S\' -> true.')
    component_somatic: typing.Optional[bool] = Field(default=None, description='True if the \'Components:\' line includes \'S\'. Example: \'Components: V, S\' -> true.')
    component_material: typing.Optional[bool] = Field(default=None, description='True if the \'Components:\' line includes \'M\'. If the block shows materials in parentheses, set this true.')
    material_components: typing.Optional[str] = Field(default=None, description='If component_material is true and the block lists materials (usually in parentheses after \'M\'), copy that materials text verbatim (without inventing). Null if no materials text is visible.')
    is_ritual: typing.Optional[bool] = Field(default=None, description='True if the header or component line marks the spell as a ritual (often \'(ritual)\' next to the level/school). Otherwise false.')
    details: typing.Optional[str] = Field(default=None, description='Non-empty: include (1) a 2–5 sentence mechanical summary and (2) the visible rules text best-effort. Must include an explicit \'At Higher Levels:\' paragraph if present.')

class ToolCall(BaseModel):
    tool_name: typing.Optional[str] = Field(default=None, description='Name of the downstream tool the executor should invoke (stable identifier, not natural language).')
    arguments: typing.Optional[str] = Field(default=None, description='Serialized arguments payload for the tool call (typically JSON or another tool-specific encoding).')
    reason: typing.Optional[str] = Field(default=None, description='Optional brief justification for why this tool call is needed, for debugging and audit logs.')
    requires_dm_privileges: typing.Optional[bool] = Field(default=None, description='True if this tool call should only be executed when the requester has DM privileges in the current Discord context.')

# #########################################################################
# Generated type aliases (0)
# #########################################################################
