# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from . import types
from . import stream_types


type_map = {

    "types.CharacterSheetIngestionError": types.CharacterSheetIngestionError,
    "stream_types.CharacterSheetIngestionError": stream_types.CharacterSheetIngestionError,

    "types.CharacterSheetIngestionResult": types.CharacterSheetIngestionResult,
    "stream_types.CharacterSheetIngestionResult": stream_types.CharacterSheetIngestionResult,

    "types.CharacterSheetIngestionSummary": types.CharacterSheetIngestionSummary,
    "stream_types.CharacterSheetIngestionSummary": stream_types.CharacterSheetIngestionSummary,

    "types.DiceTerm": types.DiceTerm,
    "stream_types.DiceTerm": stream_types.DiceTerm,

    "types.PlannerDecision": types.PlannerDecision,
    "stream_types.PlannerDecision": stream_types.PlannerDecision,

    "types.RollPlan": types.RollPlan,
    "stream_types.RollPlan": stream_types.RollPlan,

    "types.SpellInsertRow": types.SpellInsertRow,
    "stream_types.SpellInsertRow": stream_types.SpellInsertRow,

    "types.ToolCall": types.ToolCall,
    "stream_types.ToolCall": stream_types.ToolCall,


    "types.CharacterSheetIngestionErrorType": types.CharacterSheetIngestionErrorType,

    "types.DamageType": types.DamageType,

    "types.RollMode": types.RollMode,

    "types.SaveAbility": types.SaveAbility,

}